import {
  LucideIcon,
  Settings,
  GitBranch,
  FileText,
  Shield,
  Box,
  Flag,
  Star,
  Coins,
  Key,
  Podcast,
  Calendar,
  LayoutDashboard,
  Building,
  Layers,
  Users,
  Book,
  UserCircle,
  User,
  Archive,
  History,
  Speech,
  Share,
  FileSearch,
  MessageCircle,
  Grid,
  Cog,
  Database,
  Hash,
  Workflow,
  MapPin,
  Map,
  Activity,
  UserCog,
  Group,
  Ticket,
  Layers2,
  Clock,
  Ruler,
  Users2,
  Warehouse,
  Sliders,
  Calculator,
  Scale,
  Grid3x3,
  FileBarChart,
  List,
  CalendarClock,
  AlignLeft,
  CheckCircle,
  ListCheck,
  Cpu,
  Link,
  Banknote,
  Fuel,
  Store,
  Handshake,
  CalendarCheck,
  File,
  Check,
  Pause,
  ArrowDown,
  ChartLine,
  FilePen,
  BadgeDollarSign,
  ChartColumn,
  Boxes,
  Clipboard,
  ClipboardCheck,
  ShoppingCart,
  PackageOpen,
  Tags,
  Edit,
  Truck,
  Droplet,
  Server,
  DollarSign,
  CreditCard,
  IdCard,
  CheckSquare,
  Landmark,
  ReceiptIndianRupee,
  ChartNoAxesCombined,
  SquareUserRound,
  BadgeIndianRupee,
  HousePlus,
  TrendingUpDown,
  BadgePercent,
  CalendarSync,
  Dock,
  FolderGit2,
  UserPlus,
  HandCoins,
  BookUser,
  Building2,
  CircleUserRound,
  UserRoundCheck,
  HandHeart,
  ShieldCheck,
  BadgeCheck,
  TriangleAlert,
  MapPinned,
  FileCheck,
  SmartphoneNfc,
  MapPinHouse,
  MessageSquare,
  MessageCircleCode,
  Bell,
  ListTodo,
  MessageSquareDiff,
  IndianRupee,
  UserCheck,
  GlobeLock,
  UserSearch,
  House,
  SquarePen,
  FileLock2,
  ScrollText,
  NotepadText,
  Receipt,
  Command,
  ClipboardPlus,
  School,
  NotebookPen,
  UserRound,
  Ambulance,
  Mail,
  UserRoundPlus,
  NotebookText,
  Files,
  FileCheck2,
  UserRoundCog,
  FilePenLine,
  TextSearch,
  BellPlus,
  FileBadge,
  FolderCog,
  CircleDollarSign,
  UsersRound,
  CircleCheck,
  MessageCircleQuestion,
  PencilRuler,
  Euro,
  ChartColumnStacked,
  SquareSigma,
  GraduationCap,
  ShieldQuestion,
  Waypoints,
  FileClock,
  SquareStack,
  ChevronsUp,
  BanknoteArrowDown,
  BookMarked,
  ChartColumnBig,
  FolderSymlink,
  UserRoundSearch,
  CircleGauge,
  SearchCode,
  CopyCheck,
  MonitorCog,
  KeyRound,
  UserLock,
  ShieldAlert,
  RotateCcwKey,
  ListOrdered,
  Tv,
  Router,
  Route,
  RockingChair
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  settings: Settings,
  'git-branch': GitBranch,
  'file-text': FileText,
  shield: Shield,
  box: Box,
  flag: Flag,
  star: Star,
  coins: Coins,
  key: Key,
  podcast: Podcast,
  calendar: Calendar,
  'layout-dashboard': LayoutDashboard,
  building: Building,
  layers: Layers,
  users: Users,
  book: Book,
  'user-circle': UserCircle,
  user: User,
  archive: Archive,
  history: History,
  speech: Speech,
  share: Share,
  'file-search': FileSearch,
  'message-circle': MessageCircle,
  grid: Grid,
  cog: Cog,
  database: Database,
  hash: Hash,
  workflow: Workflow,
  'map-pin': MapPin,
  map: Map,
  activity: Activity,
  'user-cog': UserCog,
  group: Group,
  ticket: Ticket,
  'layers-2': Layers2,
  clock: Clock,
  ruler: Ruler,
  'users-2': Users2,
  warehouse: Warehouse,
  sliders: Sliders,
  calculator: Calculator,
  scale: Scale,
  'grid-3x3': Grid3x3,
  'file-bar-chart': FileBarChart,
  list: List,
  'calendar-clock': CalendarClock,
  'align-left': AlignLeft,
  'check-circle': CheckCircle,
  'list-check': ListCheck,
  cpu: Cpu,
  link: Link,
  banknote: Banknote,
  fuel: Fuel,
  store: Store,
  handshake: Handshake,
  'calendar-check': CalendarCheck,
  file: File,
  check: Check,
  pause: Pause,
  'arrow-down': ArrowDown,
  'chart-line': ChartLine,
  'file-pen': FilePen,
  'badge-dollar-sign': BadgeDollarSign,
  'chart-column': ChartColumn,
  boxes: Boxes,
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  'shopping-cart': ShoppingCart,
  'package-open': PackageOpen,
  tags: Tags,
  edit: Edit,
  truck: Truck,
  droplet: Droplet,
  server: Server,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  'id-card': IdCard,
  'check-square': CheckSquare,
  landmark: Landmark,
  'receipt-indian-rupee': ReceiptIndianRupee,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'square-user-round': SquareUserRound,
  'badge-indian-rupee': BadgeIndianRupee,
  'house-plus': HousePlus,
  'trending-up-down': TrendingUpDown,
  'badge-percent': BadgePercent,
  'calendar-sync': CalendarSync,
  dock: Dock,
  'folder-git-2': FolderGit2,
  'user-plus': UserPlus,
  'hand-coins': HandCoins,
  'book-user': BookUser,
  'building-2': Building2,
  'circle-user-round': CircleUserRound,
  'user-round-check': UserRoundCheck,
  'hand-heart': HandHeart,
  'shield-check': ShieldCheck,
  'badge-check': BadgeCheck,
  'triangle-alert': TriangleAlert,
  'map-pinned': MapPinned,
  'file-check': FileCheck,
  'smartphone-nfc': SmartphoneNfc,
  'map-pin-house': MapPinHouse,
  'messages-square': MessageSquare,
  'message-circle-code': MessageCircleCode,
  bell: Bell,
  'list-todo': ListTodo,
  'message-square-diff': MessageSquareDiff,
  'indian-rupee': IndianRupee,
  'user-check': UserCheck,
  'globe-lock': GlobeLock,
  'user-search': UserSearch,
  house: House,
  'square-pen': SquarePen,
  'file-lock-2': FileLock2,
  'scroll-text': ScrollText,
  'notepad-text': NotepadText,
  receipt: Receipt,
  command: Command,
  'clipboard-plus': ClipboardPlus,
  school: School,
  'notebook-pen': NotebookPen,
  'user-round': UserRound,
  ambulance: Ambulance,
  mail: Mail,
  'user-round-plus': UserRoundPlus,
  'notebook-text': NotebookText,
  files: Files,
  'file-check-2': FileCheck2,
  'user-round-cog': UserRoundCog,
  'file-pen-line': FilePenLine,
  'text-search': TextSearch,
  'bell-plus': BellPlus,
  'file-badge': FileBadge,
  'folder-cog': FolderCog,
  'circle-dollar-sign': CircleDollarSign,
  'users-round': UsersRound,
  'circle-check': CircleCheck,
  'message-circle-question': MessageCircleQuestion,
  'pencil-ruler': PencilRuler,
  euro: Euro,
  'chart-column-stacked': ChartColumnStacked,
  'square-sigma': SquareSigma,
  'graduation-cap': GraduationCap,
  'shield-question': ShieldQuestion,
  waypoints: Waypoints,
  'file-clock': FileClock,
  'square-stack': SquareStack,
  'chevrons-up': ChevronsUp,
  'banknote-arrow-down': BanknoteArrowDown,
  'book-marked': BookMarked,
  'chart-column-big': ChartColumnBig,
  'folder-symlink': FolderSymlink,
  'calendar-check-2': CalendarCheck,
  'user-round-search': UserRoundSearch,
  'circle-gauge': CircleGauge,
  'shield-question-mark': ShieldQuestion,
  'search-code': SearchCode,
  'copy-check': CopyCheck,
  'monitor-cog': MonitorCog,
  'key-round': KeyRound,
  'user-lock': UserLock,
  'shield-alert': ShieldAlert,
  'rotate-ccw-key': RotateCcwKey,
  'list-ordered': ListOrdered,
  tv: Tv,
  router: Router,
  route: Route,
  'rocking-chair': RockingChair,
 
};
